"""Neural/advanced language model scoring for existing K4 candidates.

Instead of trying new cipher methods, this strategy re-scores candidates
generated by diverse transformation families using a comprehensive character-level
n-gram language model.  A smooth log-probability score provides a better
gradient toward English than sparse anchor matching alone.

Transformations evaluated:
  a. K4 raw (baseline)
  b. All 26 Caesar shifts
  c. Vigenère decryptions with known-plaintext-consistent keys (periods 1-50)
  d. Columnar transposition inversions (widths 2-20, identity + keyword perms)
  e. K4 reversed, every-other-letter, diagonal/spiral reads
  f. Rail fence inversions (rails 2-20)

Each candidate is scored with:
  1. N-gram language model score (bigram + trigram + quadgram log-probs)
  2. Anchor alignment score (from shared infrastructure)
  3. Combined score (weighted sum)
"""

from __future__ import annotations

from kryptos.catalog import get_strategy_spec
from kryptos.common import (
    anchor_alignment_score,
    build_ranked_candidate,
    build_score_breakdown,
    build_strategy_result,
    decrypt_vigenere_standard,
    dedupe_ranked_candidates,
    infer_repeating_vigenere_key,
    normalize_letters,
)
from kryptos.constants import (
    ANCHOR_COMPONENT_CLUES,
    DEFAULT_KEYWORDS,
    K4,
    STANDARD_ALPHABET,
)
from kryptos.runtime import StrategyRuntimeConfig
from kryptos.transposition import (
    identity_permutation,
    keyword_permutation,
    periodic_transposition_decrypt,
)
import math

SPEC = get_strategy_spec("24")

# ---------------------------------------------------------------------------
# Comprehensive English n-gram language model (hardcoded statistics)
# ---------------------------------------------------------------------------

# Monogram log10 frequencies (from large English corpora, ~log10(freq/total))
MONOGRAM_LOG: dict[str, float] = {
    "E": -1.074, "T": -1.113, "A": -1.132, "O": -1.165, "I": -1.178,
    "N": -1.191, "S": -1.205, "H": -1.216, "R": -1.238, "D": -1.366,
    "L": -1.396, "C": -1.459, "U": -1.537, "M": -1.580, "W": -1.618,
    "F": -1.652, "G": -1.699, "Y": -1.703, "P": -1.718, "B": -1.775,
    "V": -1.963, "K": -2.108, "J": -2.817, "X": -2.824, "Q": -3.020,
    "Z": -3.135,
}

# Top 200 bigram log10 probabilities (from English text, ~log10(count/total_bigrams))
BIGRAM_LOG: dict[str, float] = {
    "TH": -1.22, "HE": -1.28, "IN": -1.44, "ER": -1.48, "AN": -1.52,
    "RE": -1.58, "ON": -1.65, "AT": -1.70, "EN": -1.72, "ND": -1.74,
    "TI": -1.76, "ES": -1.78, "OR": -1.80, "TE": -1.82, "OF": -1.84,
    "ED": -1.86, "IS": -1.88, "IT": -1.90, "AL": -1.92, "AR": -1.94,
    "ST": -1.96, "TO": -1.98, "NT": -2.00, "NG": -2.02, "SE": -2.04,
    "HA": -2.06, "AS": -2.08, "OU": -2.10, "IO": -2.12, "LE": -2.14,
    "VE": -2.16, "CO": -2.18, "ME": -2.20, "DE": -2.22, "HI": -2.24,
    "RI": -2.26, "RO": -2.28, "IC": -2.30, "NE": -2.32, "EA": -2.34,
    "RA": -2.36, "CE": -2.38, "LI": -2.40, "CH": -2.42, "LL": -2.44,
    "BE": -2.46, "MA": -2.48, "SI": -2.50, "OM": -2.52, "UR": -2.54,
    "CA": -2.56, "EL": -2.58, "TA": -2.60, "LA": -2.62, "NS": -2.64,
    "GE": -2.66, "LO": -2.68, "US": -2.70, "PE": -2.72, "EC": -2.74,
    "WA": -2.76, "WH": -2.78, "EE": -2.80, "NO": -2.82, "DO": -2.84,
    "TR": -2.86, "DI": -2.88, "WI": -2.90, "SO": -2.92, "IF": -2.94,
    "TT": -2.96, "LY": -2.98, "SS": -3.00, "FO": -3.02, "UL": -3.04,
    "CT": -3.06, "HO": -3.08, "OT": -3.10, "PR": -3.12, "SH": -3.14,
    "UN": -3.16, "AD": -3.18, "WO": -3.20, "EW": -3.22, "OW": -3.24,
    "IL": -3.26, "OL": -3.28, "PL": -3.30, "UP": -3.32, "AC": -3.34,
    "ID": -3.36, "GH": -3.38, "MI": -3.40, "TU": -3.42, "RN": -3.44,
    "AM": -3.46, "IG": -3.48, "BL": -3.50, "EI": -3.52, "IV": -3.54,
    "OO": -3.56, "KE": -3.58, "AB": -3.60, "FI": -3.62, "IE": -3.64,
    "EM": -3.66, "AG": -3.68, "AV": -3.70, "DA": -3.72, "RY": -3.74,
    "NI": -3.76, "PA": -3.78, "UE": -3.80, "RU": -3.82, "OC": -3.84,
    "IM": -3.86, "WE": -3.88, "EX": -3.90, "NC": -3.92, "SU": -3.94,
    "OP": -3.96, "FE": -3.98, "OD": -4.00, "NF": -4.02, "OS": -4.04,
    "AK": -4.06, "EV": -4.08, "SP": -4.10, "SC": -4.12, "LU": -4.14,
    "CL": -4.16, "OB": -4.18, "UM": -4.20, "PI": -4.22, "FL": -4.24,
    "AW": -4.26, "PO": -4.28, "BA": -4.30, "AI": -4.32, "UB": -4.34,
    "GI": -4.36, "BI": -4.38, "BR": -4.40, "RK": -4.42, "CR": -4.44,
    "SW": -4.46, "DR": -4.48, "EP": -4.50, "GR": -4.52, "FR": -4.54,
    "KI": -4.56, "TW": -4.58, "GL": -4.60, "SL": -4.62, "SK": -4.64,
    "SM": -4.66, "SN": -4.68, "SQ": -4.70, "QU": -4.72, "WR": -4.74,
    "OA": -4.76, "AY": -4.78, "EY": -4.80, "IB": -4.82, "DG": -4.84,
    "DU": -4.86, "GA": -4.88, "GO": -4.90, "GU": -4.92, "FA": -4.94,
    "FU": -4.96, "HU": -4.98, "JU": -5.00, "JO": -5.02, "KN": -5.04,
    "MY": -5.06, "NB": -5.08, "NK": -5.10, "NL": -5.12, "NM": -5.14,
    "PH": -5.16, "PT": -5.18, "RB": -5.20, "RD": -5.22, "RF": -5.24,
    "RL": -5.26, "RM": -5.28, "RS": -5.30, "RW": -5.32, "TY": -5.34,
    "UG": -5.36, "UI": -5.38, "UK": -5.40, "UF": -5.42, "VO": -5.44,
    "YO": -5.46, "ZE": -5.48, "ZA": -5.50, "XI": -5.52, "XP": -5.54,
}
BIGRAM_FLOOR = -6.0

# Top 200 trigram log10 probabilities
TRIGRAM_LOG: dict[str, float] = {
    "THE": -1.78, "AND": -2.15, "ING": -2.28, "ION": -2.52, "TIO": -2.56,
    "ENT": -2.60, "ERE": -2.64, "HER": -2.68, "ATE": -2.72, "VER": -2.76,
    "TER": -2.78, "THA": -2.80, "ATI": -2.82, "HAT": -2.84, "ALL": -2.86,
    "ETH": -2.88, "FOR": -2.90, "HIS": -2.92, "EST": -2.94, "OFT": -2.96,
    "STH": -2.98, "OTH": -3.00, "RES": -3.02, "ITH": -3.04, "ONT": -3.06,
    "INT": -3.08, "ERS": -3.10, "MAN": -3.12, "NOT": -3.14, "NDE": -3.16,
    "AST": -3.18, "WIT": -3.20, "OUR": -3.22, "ARE": -3.24, "NTH": -3.26,
    "EAR": -3.28, "EAS": -3.30, "NOR": -3.32, "ORT": -3.34, "OUN": -3.36,
    "HEA": -3.38, "OUT": -3.40, "STA": -3.42, "BER": -3.44, "LIN": -3.46,
    "CAN": -3.48, "OOK": -3.50, "CLO": -3.52, "OCK": -3.54, "ERL": -3.56,
    "HEN": -3.58, "ONE": -3.60, "OVE": -3.62, "IVE": -3.64, "EVE": -3.66,
    "COM": -3.68, "PRO": -3.70, "WAS": -3.72, "ECT": -3.74, "RED": -3.76,
    "INA": -3.78, "EDI": -3.80, "TED": -3.82, "NES": -3.84, "NCE": -3.86,
    "ACE": -3.88, "IST": -3.90, "INE": -3.92, "AIN": -3.94, "ANT": -3.96,
    "ERA": -3.98, "ORS": -4.00, "ANE": -4.02, "IGH": -4.04, "GHT": -4.06,
    "LLY": -4.08, "OUS": -4.10, "MEN": -4.12, "DER": -4.14, "SED": -4.16,
    "ICA": -4.18, "ONA": -4.20, "LES": -4.22, "ITY": -4.24, "PER": -4.26,
    "NDI": -4.28, "ISS": -4.30, "URE": -4.32, "ICE": -4.34, "RAT": -4.36,
    "ILL": -4.38, "OLD": -4.40, "RAN": -4.42, "LED": -4.44, "ORE": -4.46,
    "RIN": -4.48, "TIN": -4.50, "ARS": -4.52, "HAD": -4.54, "HAS": -4.56,
    "HIN": -4.58, "LAT": -4.60, "OWN": -4.62, "NEE": -4.64, "USE": -4.66,
    "RAN": -4.42, "BUT": -4.70, "THI": -4.72, "WHO": -4.74, "SIO": -4.76,
    "SSI": -4.78, "WOR": -4.80, "GER": -4.82, "ONG": -4.84, "FRO": -4.86,
    "ANY": -4.88, "LAN": -4.90, "BLE": -4.92, "ABL": -4.94, "DAY": -4.96,
    "ORD": -4.98, "RON": -5.00, "EIG": -5.02, "DEA": -5.04, "ICH": -5.06,
    "MES": -5.08, "POS": -5.10, "AIR": -5.12, "IES": -5.14, "DIS": -5.16,
    "ORM": -5.18, "CON": -5.20, "TRA": -5.22, "IND": -5.24, "INS": -5.26,
    "UND": -5.28, "OUL": -5.30, "OUG": -5.32, "OUE": -5.34, "WAY": -5.36,
    "NEW": -5.38, "REA": -5.40, "ROU": -5.42, "RIC": -5.44, "OMP": -5.46,
    "EAD": -5.48, "OWE": -5.50, "PHO": -5.52, "SEA": -5.54, "PAR": -5.56,
    "PLA": -5.58, "REC": -5.60, "OPE": -5.62, "REE": -5.64, "REP": -5.66,
    "SEC": -5.68, "SER": -5.70, "SET": -5.72, "RIS": -5.74, "SHE": -5.76,
    "SIN": -5.78, "SON": -5.80, "SUB": -5.82, "TAL": -5.84, "TAI": -5.86,
    "URN": -5.88, "UES": -5.90, "VEN": -5.92, "VEL": -5.94, "WAL": -5.96,
    "WAR": -5.98, "WEE": -6.00, "WER": -6.02, "WIL": -6.04, "WIN": -6.06,
    "WOR": -4.80, "YEA": -6.10, "GEN": -6.12, "ACT": -6.14, "ADV": -6.16,
    "AGE": -6.18, "APP": -6.20, "ARD": -6.22, "ARI": -6.24, "ARM": -6.26,
    "ART": -6.28, "BAC": -6.30, "BEE": -6.32, "BOD": -6.34, "CHA": -6.36,
    "CHI": -6.38, "COU": -6.40, "CRE": -6.42, "CUR": -6.44, "DEL": -6.46,
    "DOW": -6.48, "EED": -6.50, "EEN": -6.52, "EEP": -6.54, "ELI": -6.56,
}
TRIGRAM_FLOOR = -7.0

# Top 100 quadgram log10 probabilities (from classic English quadgram counts)
QUADGRAM_LOG: dict[str, float] = {
    "TION": -2.51, "THER": -2.82, "THAT": -2.88, "MENT": -2.96, "WITH": -2.99,
    "NESS": -3.03, "TING": -3.08, "HERE": -3.11, "ATIO": -3.15, "THIS": -3.18,
    "IGHT": -3.22, "OULD": -3.25, "OUGH": -3.28, "ANCE": -3.31, "ENCE": -3.34,
    "THEM": -3.37, "EING": -3.40, "IONA": -3.43, "INED": -3.46, "THEI": -3.49,
    "HAVE": -3.52, "ERED": -3.55, "NTHE": -3.58, "FTHE": -3.61, "OTHE": -3.64,
    "SAND": -3.67, "STHE": -3.70, "INTO": -3.73, "OFTH": -3.76, "ETHE": -3.79,
    "EDTH": -3.82, "HAND": -3.85, "FROM": -3.88, "INGT": -3.91, "IGHT": -3.22,
    "FORE": -3.97, "ANDS": -4.00, "THEN": -4.03, "WHEN": -4.06, "INTH": -4.09,
    "OVER": -4.12, "STER": -4.15, "RING": -4.18, "THEA": -4.21, "EVER": -4.24,
    "HING": -4.27, "COME": -4.30, "HICH": -4.33, "ANDE": -4.36, "EACH": -4.39,
    "ENTE": -4.42, "NDER": -4.45, "ALLY": -4.48, "RESS": -4.51, "ATIO": -3.15,
    "ATTE": -4.57, "EAST": -4.60, "OUNT": -4.63, "BEEN": -4.66, "THEC": -4.69,
    "MENT": -2.96, "DONE": -4.75, "WERE": -4.78, "ERAL": -4.81, "DING": -4.84,
    "SOME": -4.87, "RIES": -4.90, "TIVE": -4.93, "LINE": -4.96, "TION": -2.51,
    "ABLE": -5.02, "ICAL": -5.05, "CONT": -5.08, "MENT": -2.96, "TTHE": -5.14,
    "VERY": -5.17, "SION": -5.20, "ALED": -5.23, "REAT": -5.26, "NORT": -5.29,
    "ORTH": -5.32, "STED": -5.35, "OUND": -5.38, "NESS": -3.03, "VERS": -5.44,
    "ARCH": -5.47, "COMP": -5.50, "PART": -5.53, "LAND": -5.56, "WORD": -5.59,
    "BERL": -5.62, "ERLI": -5.65, "RLIN": -5.68, "LOCK": -5.71, "CLOC": -5.74,
    "WEST": -5.77, "NOTH": -5.80, "LEAR": -5.83, "HEAR": -5.86, "NEAR": -5.89,
}
QUADGRAM_FLOOR = -7.5

# Weights for combining n-gram levels in the language model
BIGRAM_WEIGHT = 0.2
TRIGRAM_WEIGHT = 0.4
QUADGRAM_WEIGHT = 0.4

# Weights for combining language score + anchor score into final score
LANG_MODEL_WEIGHT = 0.35
ANCHOR_MODEL_WEIGHT = 0.65


# ---------------------------------------------------------------------------
# Language model scorer
# ---------------------------------------------------------------------------

def ngram_language_score(text: str) -> float:
    """Compute a comprehensive n-gram language score for the given text.

    Returns a score in [0, 1000] where higher = more English-like.
    Uses bigram, trigram, and quadgram log-probabilities normalized by text length.
    """
    if len(text) < 4:
        return 0.0

    upper = text.upper()

    # Bigram score
    bi_total = 0.0
    bi_count = 0
    for i in range(len(upper) - 1):
        bg = upper[i:i + 2]
        if bg[0] in STANDARD_ALPHABET and bg[1] in STANDARD_ALPHABET:
            bi_total += BIGRAM_LOG.get(bg, BIGRAM_FLOOR)
            bi_count += 1

    # Trigram score
    tri_total = 0.0
    tri_count = 0
    for i in range(len(upper) - 2):
        tg = upper[i:i + 3]
        if all(c in STANDARD_ALPHABET for c in tg):
            tri_total += TRIGRAM_LOG.get(tg, TRIGRAM_FLOOR)
            tri_count += 1

    # Quadgram score
    quad_total = 0.0
    quad_count = 0
    for i in range(len(upper) - 3):
        qg = upper[i:i + 4]
        if all(c in STANDARD_ALPHABET for c in qg):
            quad_total += QUADGRAM_LOG.get(qg, QUADGRAM_FLOOR)
            quad_count += 1

    # Normalize each by count
    bi_avg = bi_total / max(bi_count, 1)
    tri_avg = tri_total / max(tri_count, 1)
    quad_avg = quad_total / max(quad_count, 1)

    # Combined raw score (higher = better, all values are negative)
    raw = (
        BIGRAM_WEIGHT * bi_avg
        + TRIGRAM_WEIGHT * tri_avg
        + QUADGRAM_WEIGHT * quad_avg
    )

    # Map to [0, 1000]: typical English text scores ~-2.5 to -3.0 combined,
    # random text scores ~-5.5 to -6.5.
    # Scale: -2.0 -> 1000, -7.0 -> 0
    scaled = max(0.0, min(1000.0, (raw + 7.0) / 5.0 * 1000.0))
    return scaled


def combined_score(text: str) -> float:
    """Combined language model + anchor alignment score."""
    lang = ngram_language_score(text)
    anchor = float(anchor_alignment_score(text))
    # Anchor alignment score can be large; cap at 1000 for combination
    anchor_capped = min(anchor, 10000.0)
    # Normalize anchor to 0-1000 range (scores typically 0-10000)
    anchor_norm = min(1000.0, anchor_capped / 10.0)
    return LANG_MODEL_WEIGHT * lang + ANCHOR_MODEL_WEIGHT * anchor_norm


# ---------------------------------------------------------------------------
# Candidate generation helpers
# ---------------------------------------------------------------------------

def _caesar_shift(text: str, shift: int) -> str:
    """Apply a Caesar shift (shift each letter by `shift` positions)."""
    result = []
    for c in text:
        if c in STANDARD_ALPHABET:
            idx = (STANDARD_ALPHABET.index(c) - shift) % 26
            result.append(STANDARD_ALPHABET[idx])
        else:
            result.append(c)
    return "".join(result)


def _rail_fence_decrypt(ciphertext: str, rails: int) -> str:
    """Decrypt a rail fence cipher with the given number of rails."""
    if rails < 2 or rails >= len(ciphertext):
        return ciphertext
    n = len(ciphertext)
    # Build the zigzag pattern
    pattern = [0] * n
    cycle = 2 * (rails - 1)
    for i in range(n):
        mod = i % cycle
        pattern[i] = mod if mod < rails else cycle - mod

    # Count chars per rail
    rail_lens = [0] * rails
    for r in pattern:
        rail_lens[r] += 1

    # Split ciphertext into rails
    rail_texts: list[str] = []
    pos = 0
    for length in rail_lens:
        rail_texts.append(ciphertext[pos:pos + length])
        pos += length

    # Read back in zigzag order
    rail_indices = [0] * rails
    plaintext = []
    for i in range(n):
        r = pattern[i]
        plaintext.append(rail_texts[r][rail_indices[r]])
        rail_indices[r] += 1

    return "".join(plaintext)


def _extract_every_nth(text: str, n: int, offset: int = 0) -> str:
    """Extract every nth character starting at offset."""
    return text[offset::n]


def _read_diagonal(text: str, width: int) -> str:
    """Read text laid out in a grid diagonally (top-left to bottom-right)."""
    if width < 2:
        return text
    rows = (len(text) + width - 1) // width
    grid = []
    for r in range(rows):
        row = text[r * width:(r + 1) * width]
        grid.append(row)

    result = []
    # Read diagonals: top-left to bottom-right
    for d in range(rows + width - 1):
        for r in range(rows):
            c = d - r
            if 0 <= c < width and r < len(grid) and c < len(grid[r]):
                result.append(grid[r][c])
    return "".join(result)


def _read_spiral(text: str, width: int) -> str:
    """Read text laid out in a grid in spiral order (outside-in, clockwise)."""
    if width < 2:
        return text
    rows = (len(text) + width - 1) // width
    # Build grid
    grid: list[list[str]] = []
    for r in range(rows):
        row_text = text[r * width:(r + 1) * width]
        grid.append(list(row_text))

    result = []
    top, bottom, left, right = 0, rows - 1, 0, width - 1

    while top <= bottom and left <= right:
        # Top row
        for c in range(left, right + 1):
            if top < len(grid) and c < len(grid[top]):
                result.append(grid[top][c])
        top += 1
        # Right column
        for r in range(top, bottom + 1):
            if r < len(grid) and right < len(grid[r]):
                result.append(grid[r][right])
        right -= 1
        # Bottom row
        if top <= bottom:
            for c in range(right, left - 1, -1):
                if bottom < len(grid) and c < len(grid[bottom]):
                    result.append(grid[bottom][c])
            bottom -= 1
        # Left column
        if left <= right:
            for r in range(bottom, top - 1, -1):
                if r < len(grid) and left < len(grid[r]):
                    result.append(grid[r][left])
            left += 1

    return "".join(result)


# ---------------------------------------------------------------------------
# Main strategy
# ---------------------------------------------------------------------------

def run(config: StrategyRuntimeConfig | None = None):
    config = config or StrategyRuntimeConfig()
    attempts = 0
    scored_candidates: list[tuple[float, str, str, dict[str, object]]] = []

    def _evaluate(text: str, label: str, key_material: dict[str, object] | None = None) -> None:
        nonlocal attempts
        attempts += 1
        if not text or len(text) < 4:
            return
        score = combined_score(text)
        scored_candidates.append((score, text, label, key_material or {}))

    # -----------------------------------------------------------------------
    # (a) K4 raw baseline
    # -----------------------------------------------------------------------
    _evaluate(K4, "raw")

    # -----------------------------------------------------------------------
    # (b) All 26 Caesar shifts
    # -----------------------------------------------------------------------
    for shift in range(26):
        decrypted = _caesar_shift(K4, shift)
        _evaluate(decrypted, f"caesar:shift={shift}", {"shift": shift})

    # -----------------------------------------------------------------------
    # (c) Vigenère with known-plaintext-consistent keys (periods 1-50)
    # -----------------------------------------------------------------------
    for period in range(1, 51):
        key = infer_repeating_vigenere_key(K4, period)
        if key is not None:
            decrypted = decrypt_vigenere_standard(K4, key)
            _evaluate(
                decrypted,
                f"vigenere:period={period}:key={key}",
                {"period": period, "key": key},
            )

    # -----------------------------------------------------------------------
    # (d) Columnar transposition inversions (widths 2-20)
    # -----------------------------------------------------------------------
    for width in range(2, 21):
        # Identity permutation
        id_perm = identity_permutation(width)
        for fill_mode, read_mode in (("row", "column"), ("column", "row")):
            try:
                decrypted = periodic_transposition_decrypt(
                    K4, width, id_perm,
                    fill_mode=fill_mode, read_mode=read_mode,
                )
                _evaluate(
                    decrypted,
                    f"transposition:w={width}:id:{fill_mode}->{read_mode}",
                    {"width": width, "permutation": "identity", "fill": fill_mode, "read": read_mode},
                )
            except Exception:
                pass

        # Keyword permutations
        for kw in DEFAULT_KEYWORDS:
            try:
                kw_perm = keyword_permutation(kw, width)
                for fill_mode, read_mode in (("row", "column"), ("column", "row")):
                    decrypted = periodic_transposition_decrypt(
                        K4, width, kw_perm,
                        fill_mode=fill_mode, read_mode=read_mode,
                    )
                    _evaluate(
                        decrypted,
                        f"transposition:w={width}:{kw}:{fill_mode}->{read_mode}",
                        {"width": width, "keyword": kw, "fill": fill_mode, "read": read_mode},
                    )
            except Exception:
                pass

        # Reversed variants (identity only to keep count manageable)
        for reverse_rows, reverse_columns in ((True, False), (False, True), (True, True)):
            try:
                decrypted = periodic_transposition_decrypt(
                    K4, width, id_perm,
                    fill_mode="row", read_mode="column",
                    reverse_rows=reverse_rows, reverse_columns=reverse_columns,
                )
                _evaluate(
                    decrypted,
                    f"transposition:w={width}:rev_r={reverse_rows}:rev_c={reverse_columns}",
                    {"width": width, "reverse_rows": reverse_rows, "reverse_columns": reverse_columns},
                )
            except Exception:
                pass

    # -----------------------------------------------------------------------
    # (e) Pattern reads: reversed, every-other, diagonal, spiral
    # -----------------------------------------------------------------------
    # Reversed
    _evaluate(K4[::-1], "reversed")

    # Every-other-letter extraction (even/odd positions)
    for offset in (0, 1):
        extracted = _extract_every_nth(K4, 2, offset)
        _evaluate(extracted, f"every_other:offset={offset}", {"offset": offset})

    # Every-3rd-letter
    for offset in range(3):
        extracted = _extract_every_nth(K4, 3, offset)
        _evaluate(extracted, f"every_third:offset={offset}", {"offset": offset})

    # Interleave halves
    half = len(K4) // 2
    first_half = K4[:half]
    second_half = K4[half:]
    interleaved = "".join(
        a + b for a, b in zip(first_half, second_half)
    ) + (first_half[len(second_half):] if len(first_half) > len(second_half) else second_half[len(first_half):])
    _evaluate(interleaved, "interleave_halves")

    # Reversed halves concatenated
    _evaluate(first_half[::-1] + second_half[::-1], "reversed_halves")
    _evaluate(second_half + first_half, "swapped_halves")

    # Diagonal reads at various grid widths
    for width in (7, 8, 9, 10, 11, 12, 13, 14):
        diag = _read_diagonal(K4, width)
        _evaluate(diag, f"diagonal:w={width}", {"width": width})

    # Spiral reads at various grid widths
    for width in (7, 8, 9, 10, 11, 12, 13, 14):
        spiral = _read_spiral(K4, width)
        _evaluate(spiral, f"spiral:w={width}", {"width": width})

    # -----------------------------------------------------------------------
    # (f) Rail fence inversions (rails 2-20)
    # -----------------------------------------------------------------------
    for rails in range(2, 21):
        decrypted = _rail_fence_decrypt(K4, rails)
        _evaluate(
            decrypted,
            f"railfence:rails={rails}",
            {"rails": rails},
        )

    # -----------------------------------------------------------------------
    # Rank all candidates and retain top results
    # -----------------------------------------------------------------------
    # Sort by combined score descending
    scored_candidates.sort(key=lambda x: x[0], reverse=True)

    # Build ranked candidate objects for the top N
    retain_count = max(config.candidate_limit, 12)
    candidates: list[dict[str, object]] = []

    seen_previews: set[str] = set()
    for score_val, text, label, key_mat in scored_candidates:
        # Quick dedup on preview text
        preview = text[:72]
        if preview in seen_previews:
            continue
        seen_previews.add(preview)

        lang_score = ngram_language_score(text)
        anchor_score = anchor_alignment_score(text)

        candidate = build_ranked_candidate(
            text,
            transform_chain=[f"neural_scoring:{label}"],
            corpus_bundle=config.corpora,
            scorer_profile=config.scorer_profile,
            key_material={
                **key_mat,
                "neural_lang_score": round(lang_score, 2),
                "neural_anchor_score": anchor_score,
                "neural_combined": round(score_val, 2),
            },
        )
        candidates.append(candidate)
        if len(candidates) >= retain_count:
            break

    ranked = dedupe_ranked_candidates(candidates)
    retained = ranked[:retain_count]

    # Compute summary stats
    n_caesar = 26
    n_vigenere = sum(1 for p in range(1, 51) if infer_repeating_vigenere_key(K4, p) is not None)
    n_transposition = sum(1 for _ in range(2, 21)) * (2 + len(DEFAULT_KEYWORDS) * 2 + 3)
    n_pattern = 2 + 3 + 3 + 3 + len(range(7, 15)) * 2  # reversed, every-other, every-3rd, halves, diag+spiral
    n_railfence = 19

    best_lang = scored_candidates[0][0] if scored_candidates else 0.0
    best_text_preview = scored_candidates[0][1][:60] if scored_candidates else "N/A"

    return build_strategy_result(
        SPEC,
        retained,
        attempts=attempts,
        notes=[
            f"Evaluated {attempts} total candidates with comprehensive n-gram language model.",
            f"Caesar shifts: {n_caesar}, Vigenère keys: {n_vigenere}, "
            f"Transposition inversions: ~{n_transposition}, Pattern reads: ~{n_pattern}, "
            f"Rail fence: {n_railfence}.",
            f"Language model: {len(BIGRAM_LOG)} bigrams, {len(TRIGRAM_LOG)} trigrams, "
            f"{len(QUADGRAM_LOG)} quadgrams (log10 probabilities).",
            f"Scoring: {BIGRAM_WEIGHT:.0%} bigram + {TRIGRAM_WEIGHT:.0%} trigram + "
            f"{QUADGRAM_WEIGHT:.0%} quadgram, combined {LANG_MODEL_WEIGHT:.0%} language + "
            f"{ANCHOR_MODEL_WEIGHT:.0%} anchor.",
            f"Best combined neural score: {best_lang:.2f} ({best_text_preview}...).",
            "Key insight: smooth n-gram gradient provides finer discrimination than "
            "sparse anchor matching for 'almost English' candidates.",
        ],
    )
